server:
  port: 8080

spring:
  application:
    name: library

  datasource:
    url: jdbc:postgresql://localhost:5435/library_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update